feat: support url rewrite
containerbase/base pull request #1210
Opened 2023-07-18 08:17 UTC by viceice

We now call back into our new cli to download the file, so the new url replacement can be applied.
Will add some more documentation too later.

- closes #1067
- https://github.com/vercel/pkg/issues/1861

2023-07-18 08:24 UTC, viceice commented on src/usr/local/containerbase/utils/cache.sh
> +      env >&2
```suggestion
```

ups

2023-07-18 09:17 UTC, Chumper approved these changes

2023-07-18 09:18 UTC, Chumper commented
We can phase out the bats tests whenever we replace functionality with typescript

2023-07-18 09:24 UTC, viceice commented
> We can phase out the bats tests whenever we replace functionality with typescript

fixed the tests. I'm not sure if i need the file delete 🤔

2023-07-18 11:39 UTC, viceice commented on src/cli/services/env.service.ts
> +
```suggestion
```

2023-07-18 11:46 UTC, viceice commented on README.md
> +Almost all tools are noew supported.
```suggestion
Almost all tools are now supported.
```

2023-07-18 11:46 UTC, viceice commented on README.md
> +Only tooles which are installed by `gem`, `npm` or `pip` are not supported.
```suggestion
Only tools which are installed by `gem`, `npm` or `pip` are not supported.
```

2023-07-18 17:09 UTC, rarkins requested changes
Can we get docs for the URL rewriting if this closes the issue?

2023-07-18 17:13 UTC, viceice commented
> Can we get docs for the URL rewriting if this closes the issue?

there are already some docs and all urls are printed on debug log level

2023-07-19 06:29 UTC, viceice commented
> P My

???

2023-07-20 05:53 UTC, rarkins commented
Not sure where that came from. Can you point me to the docs?

2023-07-20 18:16 UTC, viceice commented
> Not sure where that came from. Can you point me to the docs?

https://github.com/containerbase/base/tree/feat/url-replace#url-replacement

will create a mother extended version in later PR's.

will try to extract the base urls to variables, so I can use a test to validate docs to have a sample for each of them.

2023-07-22 10:10 UTC, rarkins approved these changes
Don't want to block this but we need conclusive docs for rewriting all URLs in a "full" image

2023-07-22 10:14 UTC, viceice commented
yes, will update docs later. currently it's best to try and error to see failed urls in logs. then it should be easy to rewrite them.

2023-07-22 10:53 UTC, merged