feat: Add helmfile tool
containerbase/base pull request #674
Opened 2023-01-17 14:41 UTC by nikolaik

This tries to add the [helmfile](https://github.com/helmfile/helmfile) tool to allow supporting lockfile updates in https://github.com/renovatebot/renovate/pull/19865

I could not manage to run the dockerfile tests for helmfile locally, but bats tests ran fine.

2023-01-18 14:11 UTC, viceice requested changes

2023-01-18 14:11 UTC, viceice commented on .github/workflows/build.yml
> +            helmfile,
revert and add to latest test image instead

2023-01-18 14:11 UTC, viceice commented on test/helmfile/Dockerfile
> +ARG IMAGE=containerbase/buildpack
just add a simple test here, as you've bats tests, which cover the relevant parts.

https://github.com/containerbase/base/blob/88af9742be55f24b1c8fd6a6cc14f6bbdf7fe7f8/test/latest/Dockerfile#L163-L189

2023-01-18 14:11 UTC, viceice commented on src/usr/local/buildpack/tools/v2/helmfile.sh
> +
```suggestion
```

done by defaults

2023-01-18 14:11 UTC, viceice commented on src/usr/local/buildpack/tools/v2/helmfile.sh
> +  local helmfile_file="${TOOL_NAME}_${TOOL_VERSION#v}_${arch}.tar.gz"
```suggestion
  local helmfile_file="${TOOL_NAME}_${TOOL_VERSION}_${arch}.tar.gz"
```
`v` is already trimmed

2023-01-18 14:11 UTC, viceice commented on src/usr/local/buildpack/tools/v2/helmfile.sh
> +
```suggestion
```
unused 🙃

2023-01-23 10:59 UTC, nikolaik commented
Thanks for the review, made a few improvements based on your feedback. Let me know if anything else needs updating

2023-01-23 11:02 UTC, viceice commented on test/helmfile/Dockerfile
> +ARG IMAGE=containerbase/buildpack
remove this file

2023-01-23 11:02 UTC, viceice commented on test/latest/Dockerfile
> +#------------------------------------------------------------------
please join to `testj`

2023-01-23 11:02 UTC, viceice commented on test/latest/Dockerfile
> +
we don't need this, only makes test slow

2023-01-23 16:56 UTC, viceice approved these changes

2023-01-23 17:09 UTC, merged